name: vandal_course
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

#These are the various libraries coming in. 
dependencies:
  flutter:
    sdk: flutter
  
  #The libraries are listed below
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  path: ^1.8.3
  cloud_firestore: ^4.8.4
  share_plus: ^7.1.0
  

#Only inside the application for development. 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:

  uses-material-design: true

